Repository openfun/cunningham, pull requests merged in 2023-07, with the labels that each got.

#113 💚(ci) fix performance issue of test job
  .circleci/config.yml
  package.json
  packages/react/package.json
  packages/tokens/package.json
  packages/tokens/src/bin/tsconfig.build.json
  packages/tokens/src/bin/tsconfig.json
  turbo.json
  yarn.lock
Labels: bug

#118 🔖(release) version packages
  .changeset/chatty-garlics-exercise.md
  .changeset/old-garlics-pull.md
  .changeset/purple-planes-mate.md
  .changeset/sweet-actors-behave.md
  apps/demo/CHANGELOG.md
  apps/demo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/tokens/CHANGELOG.md
  packages/tokens/package.json
Labels: FUN Team

#119 🐛(react) fix datagrid column unique key
  .changeset/selfish-phones-enjoy.md
  packages/react/src/components/DataGrid/index.spec.tsx
  packages/react/src/components/DataGrid/index.tsx
  packages/react/src/components/DataGrid/utils.tsx
Labels: bug, easy pick

#122 🐛(react) make DatePicker's tests no longer depend on the user's locale.
  .changeset/violet-rings-love.md
  packages/react/src/components/Forms/DatePicker/DatePicker.spec.tsx
Labels: bug
