Repository openfun/cunningham, pull requests merged in 2023-05, with the labels that each got.

#48 📦️(react) pure ESM package
  .changeset/red-chicken-provide.md
  packages/react/package.json
Labels: bug

#51 🔖(react) bump to 0.6.1
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: FUN Team

#52 🐛(react) fix storybook deploy
  packages/react/package.json
Labels: documentation, critical

#54 🏷️(react) add missing types exports
  .changeset/tender-feet-type.md
  packages/react/src/index.ts
Labels: bug

#55 🔖(release) version packages
  .changeset/tender-feet-type.md
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: FUN Team

#75 🔖(release) version packages
  .changeset/beige-cougars-crash.md
  .changeset/dry-maps-speak.md
  .changeset/fast-bulldogs-cross.md
  .changeset/giant-drinks-battle.md
  .changeset/hip-cups-drive.md
  .changeset/neat-games-whisper.md
  .changeset/sixty-beds-raise.md
  .changeset/stale-hotels-jump.md
  .changeset/swift-shoes-tell.md
  .changeset/three-days-fold.md
  .changeset/twenty-mugs-cross.md
  .changeset/unlucky-parrots-grab.md
  .changeset/wet-spiders-hide.md
  .changeset/young-cats-notice.md
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: FUN Team

#80 📝(doc) improve README
  README.md
  resources/banner.png
  resources/examples.png
Labels: documentation

#81 Doc/readme discord link
  README.md
Labels: documentation
