Repository openfun/cunningham, pull requests merged in 2023-10, with the labels that each got.

#181 🩹(react) export Popover component and its props
  .changeset/few-bats-stare.md
  packages/react/src/components/Popover/index.tsx
  packages/react/src/index.ts
Labels: bug

#185 🩹(react) export Button props
  .changeset/tough-toys-obey.md
  packages/react/src/components/Button/index.tsx
Labels: easy pick, improvement

#189 🔖(release) version packages
  .changeset/tough-toys-obey.md
  .changeset/twenty-bulldogs-whisper.md
  .changeset/yellow-ghosts-shake.md
  apps/demo/CHANGELOG.md
  apps/demo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/tokens/CHANGELOG.md
  packages/tokens/package.json
Labels: FUN Team

#186 🐛(react) fix inputs overflowing placeholder
  .changeset/soft-files-grin.md
  packages/react/src/components/Forms/Examples/EdgeCases/index.stories.tsx
  packages/react/src/components/Forms/Input/index.spec.tsx
  packages/react/src/components/Forms/LabelledBox/index.scss
  packages/react/src/components/Forms/LabelledBox/index.tsx
  packages/react/src/components/Forms/Select/index.scss
  packages/react/src/components/Forms/Select/mono.spec.tsx
  packages/react/src/components/Forms/Select/multi.spec.tsx
Labels: bug

#198 ✨(react) render Button as link
  .changeset/breezy-llamas-fail.md
  packages/react/src/components/Button/index.scss
  packages/react/src/components/Button/index.spec.tsx
  packages/react/src/components/Button/index.stories.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Forms/DatePicker/CalendarCell.tsx
Labels: feature
