Repository openfun/cunningham, pull requests merged in 2023-06, with the labels that each got.

#91 Fix eof stylesheet files
  .changeset/sweet-carrots-cheer.md
  packages/react/src/components/Accessibility/index.scss
  packages/react/src/components/Forms/Checkbox/index.scss
  packages/react/src/components/Forms/Field/index.scss
  packages/react/src/components/Forms/Input/index.scss
  packages/react/src/components/Forms/Radio/index.scss
  packages/react/src/components/Forms/Select/index.scss
  packages/react/src/components/Loader/index.scss
  packages/react/src/components/Pagination/index.scss
  packages/react/src/index.scss
Labels: improvement

#99 🔖(release) version packages
  .changeset/seven-icons-peel.md
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: FUN Team

#102 🐛(react) export `DatePicker` components
  .changeset/shiny-donkeys-cross.md
  packages/react/src/index.ts
Labels: bug

#104 🔖(release) version packages
  .changeset/shiny-donkeys-cross.md
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/tokens/CHANGELOG.md
  packages/tokens/package.json
Labels: FUN Team

#105 💄(demo) update default cunningham tokens
  .changeset/old-garlics-pull.md
  apps/demo/src/cunningham-tokens.css
  apps/demo/src/cunningham-tokens.ts
Labels: improvement

#110 🐛(react) avoid storybook errors
  packages/react/tsconfig.json
Labels: bug
